### ISSUE TITLE
Can SpSpMM back propagation be improved?

### ISSUE THREAD

**Issue by esaliya** [rusty1s/pytorch_sparse#11]
Not a bug but I am seeing a decrease in performance in the backpropagation when I changed from dense representation to sparse matrices using pytorch_sparse. After profiling using torch.utils.bottleneck, I see something like the following on a single machine. I wonder if SpSpMM backprop could be improved for performance.

```
 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       28   56.723    2.026   56.723    2.026 {method 'run_backward' of 'torch._C._EngineBase' objects}
      576    2.685    0.005    2.685    0.005 {built-in method _unique}
     1408    2.349    0.002    2.349    0.002 {method 'scatter_add_' of 'torch._C._TensorBase' objects}
      832    1.252    0.002    4.078    0.005 /anaconda3/envs/hep/lib/python3.6/site-packages/torch_sparse/spmm.py:4(spmm)
     1280    0.760    0.001    0.760    0.001 {built-in method cat}
      448    0.720    0.002    0.720    0.002 {built-in method tanh}
     1408    0.449    0.000    0.449    0.000 {method 'new_full' of 'torch._C._TensorBase' objects}
      608    0.263    0.000    0.263    0.000 {method 'matmul' of 'torch._C._TensorBase' objects}
      128    0.199    0.002    0.199    0.002 {built-in method tensor}
      576    0.111    0.000    2.900    0.005 /anaconda3/envs/hep/lib/python3.6/site-packages/torch_sparse/coalesce.py:7(coalesce)
     1536    0.069    0.000    0.069    0.000 {built-in method stack}
      608    0.060    0.000    0.330    0.001 /anaconda3/envs/hep/lib/python3.6/site-packages/torch/nn/functional.py:1336(linear)
     1472    0.058    0.000    0.058    0.000 {method 'read' of '_io.BufferedReader' objects}
  1856/32    0.044    0.000    9.348    0.292 /anaconda3/envs/hep/lib/python3.6/site-packages/torch/nn/modules/module.py:483(__call__)
     3458    0.040    0.000    0.040    0.000 {method 'reduce' of 'numpy.ufunc' objects}

```

You can see the majority of the backprop comes from SpSpMM as shown below.

```
------------------  ---------------  ---------------  ---------------  ---------------  ---------------
Name                       CPU time        CUDA time            Calls        CPU total       CUDA total
------------------  ---------------  ---------------  ---------------  ---------------  ---------------
SpSpMMBackward         359986.000us          0.000us                1     359986.000us          0.000us
SpSpMMBackward         355614.000us          0.000us                1     355614.000us          0.000us
SpSpMMBackward         346439.000us          0.000us                1     346439.000us          0.000us
SpSpMMBackward         330789.000us          0.000us                1     330789.000us          0.000us
SpSpMMBackward         318372.000us          0.000us                1     318372.000us          0.000us
SpSpMMBackward         314331.000us          0.000us                1     314331.000us          0.000us
SpSpMMBackward         304800.000us          0.000us                1     304800.000us          0.000us
SpSpMMBackward         304651.000us          0.000us                1     304651.000us          0.000us
SpSpMMBackward         302225.000us          0.000us                1     302225.000us          0.000us
SpSpMMBackward         299735.000us          0.000us                1     299735.000us          0.000us
SpSpMMBackward         299507.000us          0.000us                1     299507.000us          0.000us
SpSpMMBackward         298172.000us          0.000us                1     298172.000us          0.000us
SpSpMMBackward         298137.000us          0.000us                1     298137.000us          0.000us
SpSpMMBackward         297997.000us          0.000us                1     297997.000us          0.000us
SpSpMMBackward         297528.000us          0.000us                1     297528.000us          0.000us
```

**Comment by rusty1s** [comment]
I see what I can do.

**Comment by esaliya** [comment]
Just checking if there is an update on this thread.

Thank you,

**Comment by rusty1s** [comment]
Yes, it is still on my todo list. Sorry for the delay.

**Comment by rusty1s** [comment]
Hi, I just pushed runtime improvements to master. CPU should now be run much much faster (approx 15 times). I could also achieved small runtime improvements for GPU which could possibly be pushed further once I figure out how I fast-transpose a sparse matrix on GPU. It would be great if you could check if this fixes your performance issues, so I can craft a new release.

**Comment by esaliya** [comment]
I tried this  but when importing `torch_sparse` it complains `ModuleNotFoundError: No module named 'torch_sparse.spspmm_cpu'`

**Comment by rusty1s** [comment]
You need to reinstall

**Comment by esaliya** [comment]
Yes, I did `pip uninstall torch_sparse`. Then I took a git clone of your repo and did `pip install .` inside of it. I can try on a fresh Python env and let you know.

**Comment by esaliya** [comment]
I am still having trouble with a different error even on a new Python environment. Here's what I did.

```
conda create -n hep3 python=3.6
source activate hep3
conda install pytorch torchvision -c pytorch
cd pytorch_scatter
python setup.py install
cd ../pytorch_sparse
python setup.py install
```

Then I opened a Python console and tried,

```
from torch_sparse import transpose
```

I get the following error.

```
>>> from torch_sparse import transpose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/hep3/lib/python3.6/site-packages/torch_sparse-0.3.0-py3.6-macosx-10.7-x86_64.egg/torch_sparse/__init__.py", line 2, in <module>
  File "/anaconda3/envs/hep3/lib/python3.6/site-packages/torch_sparse-0.3.0-py3.6-macosx-10.7-x86_64.egg/torch_sparse/coalesce.py", line 2, in <module>
  File "/anaconda3/envs/hep3/lib/python3.6/site-packages/torch_scatter-1.1.2-py3.6-macosx-10.7-x86_64.egg/torch_scatter/__init__.py", line 3, in <module>
  File "/anaconda3/envs/hep3/lib/python3.6/site-packages/torch_scatter-1.1.2-py3.6-macosx-10.7-x86_64.egg/torch_scatter/mul.py", line 3, in <module>
  File "/anaconda3/envs/hep3/lib/python3.6/site-packages/torch_scatter-1.1.2-py3.6-macosx-10.7-x86_64.egg/torch_scatter/utils/ext.py", line 2, in <module>
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'
```

**Comment by rusty1s** [comment]
torch-scatter is a dependency of torch-sparse. Did you install it?

**Comment by esaliya** [comment]
Yes, I cloned it from your repo and did `python setup.py install` as shown in my script above.

**Comment by esaliya** [comment]
OK, I finally got it fixed by ditching all of my Python envs and creating a new one. Now, it's quite improved. I am seeing about 3X improvement in overall time than before.

This is really, great and thank you for the quick fix!

**Comment by jaynanavati-az** [comment]
https://github.com/rusty1s/pytorch_sparse/blob/d6564de570701e83c3bf526ed2562a8572e3b5be/torch_sparse/spspmm.py

What does **lift** do? idxA, idxB seem to have very large numbers and I get an out of memory .. indexA is of shape torch.Size([2, 17238453]) ..

**Comment by rusty1s** [comment]
This is a pretty old code, I suggest to not spend too much time looking at it. `lift` will find the union of values inside `indexA` and `indexB` by lifting values into a "nearly dense" matrix. The next iteration of implementation a has fixed this to some extend: https://github.com/rusty1s/pytorch_sparse/blob/0.4.0/torch_sparse/spspmm.py

**Comment by jaynanavati-az** [comment]
@rusty1s `lift` seems to be doing the same thing still in 0.4.0 no?
