### ISSUE TITLE
unknown:0: expecting kind 'variable' but found '.'

### ISSUE THREAD

**Issue by WilliamKRobert** [rusty1s/pytorch_sparse#142]
Hey, I have successfully installed torch==1.4.0 and torch_sparse==0.6.9 on a Jetson TX2, but when I try to import torch_sparse, I got the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch_sparse/__init__.py", line 37, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch_sparse/tensor.py", line 12, in <module>
    class SparseTensor(object):
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch/jit/__init__.py", line 1274, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch/jit/__init__.py", line 1115, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError: unknown:0: expecting kind 'variable' but found '.'
  File "/home/nvidia/gcn/lib/python3.6/site-packages/torch_sparse/tensor.py", line 32
                           col=storage._col, value=storage._value,
                           sparse_sizes=storage._sparse_sizes, is_sorted=True)
        out.storage._rowcount = storage._rowcount
        ~~~~~~~~~~~ <--- HERE
        out.storage._colptr = storage._colptr
        out.storage._colcount = storage._colcount
```

Any thoughts?

**Comment by rusty1s** [comment]
Mh, seems related to TorchScript. I suggest you remove the `@torch.jit.script` annotations in `storage.py` and `tensor.py` and try again :)

**Comment by WilliamKRobert** [comment]
Thanks! This works for me. 
I am curious if upgrading PyTorch from 1.4.0 will also do the work? And what is the side effect of removing the ```@torch.jit.script annotations```?

**Comment by rusty1s** [comment]
There's no downside if you don't plan to make use of TorchScript.

**Comment by WilliamKRobert** [comment]
Cool. Many thanks!
