### ISSUE TITLE
OSError: /home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_sparse-0.6.9-py3.7-linux-x86_64.egg/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by ShuLinaaa** [rusty1s/pytorch_sparse#149]
I encountered the following problem when calling the package

Traceback (most recent call last):
  File "/home/psdz/zxltmp/Exp-Bot/train.py", line 11, in <module>
    from dataset_botnet import BotnetDataset
  File "/home/psdz/zxltmp/Exp-Bot/dataset_botnet.py", line 11, in <module>
    from torch_geometric.data import Data, InMemoryDataset
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_sparse-0.6.9-py3.7-linux-x86_64.egg/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/psdz/anaconda3/envs/zxltmp/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/psdz/anaconda3/envs/zxltmp/lib/python3.7/site-packages/torch_sparse-0.6.9-py3.7-linux-x86_64.egg/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv

I didn't figure out the problem. Have you encountered this problem? How is it solved?
Thanks for your help!

**Comment by ShuLinaaa** [comment]
I guess it's about the CUDA version. I have torch1.9.0+cu111. My Cuda version is 11.1

**Comment by rusty1s** [comment]
This error is usually related to having an extension package installed which does not match with your PyTorch/CUDA version (in this case PyTorch 1.9.0 and CUDA 11.1). I suggest you try to un-install all related packages first (`torch-sparse`, torch-scatter`, ...) and try again. Keep in mind that you need to re-install PyG and its extensions everytime a new PyTorch version is used.

**Comment by ShuLinaaa** [comment]
Thanks for your reply! I have solved this problem by creating a new Conda environment with torch=1.8.1+cu111,  torch-geometric=1.4.3, torch-sparse=0.6.9, torch-sparse=2.0.6. I guess it occurred because I installed another version of PyTorch before. And some extension packages may not be removed clear.

**Comment by rusty1s** [comment]
Awesome :)
