### ISSUE TITLE
Error when indexing sparse tensor

### ISSUE THREAD

**Issue by TobiasSchmidtDE** [rusty1s/pytorch_sparse#160]
The latest version (`Version: 0.6.10`) with the addition of [checking the row/col tensors when initializing the SparseStorage](https://github.com/rusty1s/pytorch_sparse/pull/126) leads to a RuntimeError when trying to index zero elements:

Minimal reproducing example:
```
test  = SparseTensor(row = torch.tensor([1]), col = torch.tensor([1]), value = torch.tensor([1]), sparse_sizes=(3,3))
test[0,0]
```

Throws:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/homedirs/schmidtt/miniconda3/lib/python3.8/site-packages/torch_sparse/tensor.py", line 470, in __getitem__
    out = out.select(dim, item)
  File "/nfs/homedirs/schmidtt/miniconda3/lib/python3.8/site-packages/torch_sparse/select.py", line 9, in <lambda>
    SparseTensor.select = lambda self, dim, idx: select(self, dim, idx)
  File "/nfs/homedirs/schmidtt/miniconda3/lib/python3.8/site-packages/torch_sparse/select.py", line 6, in select
    return narrow(src, dim, start=idx, length=1)
  File "/nfs/homedirs/schmidtt/miniconda3/lib/python3.8/site-packages/torch_sparse/narrow.py", line 38, in narrow
    storage = SparseStorage(row=row, rowptr=rowptr, col=col, value=value,
  File "/nfs/homedirs/schmidtt/miniconda3/lib/python3.8/site-packages/torch_sparse/storage.py", line 63, in __init__
    assert row.max().item() < sparse_sizes[0]
RuntimeError: operation does not have an identity.
```

**Comment by TobiasSchmidtDE** [comment]
Nevermind, this has already been fixed in `>=0.6.11`
