### ISSUE TITLE
diffrent behavior between cpu and cuda

### ISSUE THREAD

**Issue by Boltzmachine** [rusty1s/pytorch_sparse#163]
when the cuda devices are invisible, my program runs well.
but when the cuda devices are available, it reports the error
```python
Traceback (most recent call last):
  File "/home/boltzmachine/THG/train.py", line 10, in <module>
    from models.simple import Simple, Share
  File "/home/boltzmachine/THG/models/simple.py", line 5, in <module>
    from .GNN import DenseGatedRGCN
  File "/home/boltzmachine/THG/models/GNN.py", line 10, in <module>
    from torch_geometric.nn.inits import glorot, zeros
  File "/home/boltzmachine/miniconda3/envs/THG/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/boltzmachine/miniconda3/envs/THG/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/boltzmachine/miniconda3/envs/THG/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/boltzmachine/miniconda3/envs/THG/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
```
I use torch 1.7.0 and cu101
I uninstalled `torch-sparse` repeatedly until there's nothing install
and I installed by
```shell
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --no-cache-dir
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --no-cache-dir
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --no-cache-dir
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --no-cache-dir
pip --no-cache-dir install torch-geometric
```

**Comment by rusty1s** [comment]
The `*_cuda.so` files should be available nonetheless, even if there is no GPU available until a job is submitted. I therefore think that the issue is that installing from wheels fails for you. How long does the installation take? Can you try again with:
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```
