### ISSUE TITLE
RuntimeError: cuda runtime error when using spspmm on cuda

### ISSUE THREAD

**Issue by shirley-wu** [rusty1s/pytorch_sparse#23]
Hi I'm trying to use spspmm on cuda to calculate the power of a 1086*1086 matrix with 66442 non-zero elements, and I encountered "cuda runtime error". The complete error message is as follows:

```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=4 : unspecified launch failure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/ana3/lib/python3.7/site-packages/torch_sparse/spspmm.py", line 26, in spspmm
    index, value = SpSpMM.apply(indexA, valueA, indexB, valueB, m, k, n)
  File "/workspace/ana3/lib/python3.7/site-packages/torch_sparse/spspmm.py", line 33, in forward
    indexC, valueC = mm(indexA, valueA, indexB, valueB, m, k, n)
  File "/workspace/ana3/lib/python3.7/site-packages/torch_sparse/spspmm.py", line 81, in mm
    m, k, n)
RuntimeError: cuda runtime error (4) : unspecified launch failure at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCCachingHostAllocator.cpp:265
```

And the operation is fine on cpu.

I'm using Ubuntu 16.04 and cuda 10.1 inside a nvidia-docker container. My Python is 3.7.3, my scipy is 1.13.0 (latest from pip), both my torch_sparse and torch_scatter are 1.3.0 (latest from pip), and my PyTorch is 1.1.0 (installed from conda)

I cannot reproduce this error using smaller matrix, so I'm afraid I have to provide the original huge matrix. If you want to reproduce this error, please download [spspmm.zip](https://github.com/rusty1s/pytorch_sparse/files/3388667/spspmm.zip) and use this snippet:

```python
import pickle
with open('spspmm.zip', 'rb') as f:    # sorry it's not really a zip file
    ei, ew, N = pickle.load(f)
from torch_sparse import spspmm
print(spspmm(ei, ew, ei, ew, N, N, N))    # works fine on cpu
print(spspmm(ei.cuda(), ew.cuda(), ei.cuda(), ew.cuda(), N, N, N))    # produce errors on cuda
```

I saw in another issue that you suggest calculate spspmm on cpu, but to me that seems ugly and inefficient. Do you have any idea how to fix this problem on cuda device? Thanks!

**Comment by shirley-wu** [comment]
Hi, I reinstalled torch_sparse from source and the problem remains. However there are some new error messages and I think this might help:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm.py", line 26, in spspmm
    index, value = SpSpMM.apply(indexA, valueA, indexB, valueB, m, k, n)
  File "/workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm.py", line 33, in forward
    indexC, valueC = mm(indexA, valueA, indexB, valueB, m, k, n)
  File "/workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm.py", line 81, in mm
    m, k, n)
RuntimeError: CUDA error: unspecified launch failure (malloc at /opt/conda/conda-bld/pytorch_1556653114079/work/c10/cuda/CUDACachingAllocator.cpp:269)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f4aa7524dc5 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x16702 (0x7f4aa4445702 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x17347 (0x7f4aa4446347 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: THCStorage_resize + 0x96 (0x7f4aabc0f706 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: THCTensor_resizeNd + 0x4d8 (0x7f4aabc25e68 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: THCudaIntTensor_catArray + 0x4f1 (0x7f4aabedacd1 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #6: at::CUDAType::_th_cat(c10::ArrayRef<at::Tensor>, long) const + 0x600 (0x7f4aabaf3d40 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #7: at::native::cat(c10::ArrayRef<at::Tensor>, long) + 0xa4 (0x7f4aa7f1d2b4 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #8: at::TypeDefault::cat(c10::ArrayRef<at::Tensor>, long) const + 0x4f (0x7f4aa81d45bf in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #9: at::native::stack(c10::ArrayRef<at::Tensor>, long) + 0x183 (0x7f4aa7f158c3 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #10: at::TypeDefault::stack(c10::ArrayRef<at::Tensor>, long) const + 0x4f (0x7f4aa81cac3f in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #11: torch::autograd::VariableType::stack(c10::ArrayRef<at::Tensor>, long) const + 0x71f (0x7f4aa511482f in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #12: <unknown function> + 0x21e7e (0x7f4a844c8e7e in /workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #13: spspmm_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, unsigned long, unsigned long, unsigned long) + 0x91c (0x7f4a844c9d31 in /workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #14: spspmm(at::Tensor, at::Tensor, at::Tensor, at::Tensor, unsigned long, unsigned long, unsigned long) + 0x11e (0x7f4a844bbfce in /workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x2064f (0x7f4a844c764f in /workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x2082e (0x7f4a844c782e in /workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #17: <unknown function> + 0x1db0c (0x7f4a844c4b0c in /workspace/ana3/lib/python3.7/site-packages/torch_sparse-0.4.0-py3.7-linux-x86_64.egg/torch_sparse/spspmm_cuda.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #24: THPFunction_apply(_object*, _object*) + 0x691 (0x7f4ad67b0891 in /workspace/ana3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #39: __libc_start_main + 0xf0 (0x7f4ae52c0830 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by rusty1s** [comment]
There seems to indeed be some problems with the CUDA version of spspmm when working with large matrices. Your example file should help to track down the error. Thank you very much!

**Comment by rusty1s** [comment]
I tracked down the error and it is caused by passing in non-coalesced sparse matrices. I therefore added an argument `coalesced` to the `spspmm` call to coalesce both sparse matrices before calling the `spspmm` kernel.
