### ISSUE TITLE
Illegal CUDA Memory Access

### ISSUE THREAD

**Issue by MichaelLLi** [rusty1s/pytorch_sparse#25]
> index1=torch.LongTensor(2,100).random_(100).cuda()
> value1=torch.Tensor(100).random_(100).cuda()
> spspmm(index1,value1,index1,value1,100,100,100)

This gives me the following error:

```
 spspmm(index1,value1,index1,value1,100,100,100)
Traceback (most recent call last):

 File "<ipython-input-18-ce50b836d1c1>", line 1, in <module>

    spspmm(index1,value1,index1,value1,100,100,100)

 File "C:\Users\Michael\Downloads\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\torch_sparse\spspmm.py", line 26, in spspmm

    index, value = SpSpMM.apply(indexA, valueA, indexB, valueB, m, k, n)

  File "C:\Users\Michael\Downloads\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\torch_sparse\spspmm.py", line 33, in forward
    indexC, valueC = mm(indexA, valueA, indexB, valueB, m, k, n)

  File "C:\Users\Michael\Downloads\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\torch_sparse\spspmm.py", line 81, in mm
    m, k, n)
RuntimeError: CUDA error: an illegal memory access was encountered (copy_device_to_device at C:/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/Copy.cu:166)
(no backtrace available) 
```
Any idea what could be causing it? I run PyTorch 1.2.0 with Windows 10, GTX 1080, and CUDA 9.0

**Comment by MichaelLLi** [comment]
Upgrading to master from the newest pip tag solved the problem

**Comment by rusty1s** [comment]
Your sparse matrices needs to be coalesced before using `spspmm`. The master version of `torch-sparse` has an additional argument to force this.
