### ISSUE TITLE
Error in torch_sparse

### ISSUE THREAD

**Issue by HosseinMousavi** [rusty1s/pytorch_sparse#250]
I received the following error:

Traceback (most recent call last):
  File "human_heart_explainer.py", line 49, in <module>
    from torch_sparse import coalesce
  File "/home/hmousavi/.conda/envs/hossein_env/lib/python3.8/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/hmousavi/.conda/envs/hossein_env/lib/python3.8/site-packages/torch/_ops.py", line 260, in load_library
    ctypes.CDLL(path)
  File "/home/hmousavi/.conda/envs/hossein_env/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/hmousavi/.conda/envs/hossein_env/lib/python3.8/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by rusty1s** [comment]
This usually indicates a mismatch in PyTorch versions, e.g., your PyTorch version is different from the one `torch-sparse` was compiled with. Can you show me your PyTorch version and how you installed `torch-sparse`?

**Comment by HosseinMousavi** [comment]
Hi @rusty1s,
Since you suggested (in slack) using wheel to install them, I uninstall those packages and install them using wheel. That worked!
Thanks!
