### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found.

### ISSUE THREAD

**Issue by yangyangdotcom** [rusty1s/pytorch_sparse#283]
While I was trying to pip install the pytorch_sparse by running the following command:
`pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+$cu113.html`

I got this error:
```
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\yihe\AppData\Local\Temp\pip-install-5rbdjmni\torch-sparse_72b0544df5b746a5a7fcfeb44fba647e\setup.py", line 8, in <module>
          import torch
        File "C:\Users\yihe\anaconda3\envs\PPI_GNN_seqvec_v6\lib\site-packages\torch\__init__.py", line 129, in <module>
          raise err
      OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\yihe\anaconda3\envs\PPI_GNN_seqvec_v6\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.
      [end of output]
```

Any idea how to solve this problem?

**Comment by rusty1s** [comment]
You need to install PyTorch beforehand.
