### ISSUE TITLE
Import error of torch_sparse on M1 Mac

### ISSUE THREAD

**Issue by realCrush** [rusty1s/pytorch_sparse#329]
I'm using M1 Pro Mac, and have envs: `torch=2.0.1, torch_geometric=2.3.1`, I install the `torch_sparse` and `torch_scatter` package with `pip install torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-2.0.1+cpu.html`, it succeed, but when import `torch_sparse`, I got error like:
```zsh
/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: dlopen(/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_scatter/_scatter_cpu.so, 0x0006): Symbol not found: __ZN2at4_ops6narrow4callERKNS_6TensorExxx
  Referenced from: <40C9EA45-5166-3704-94F1-8C3ED6EBA15C> /Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_scatter/_scatter_cpu.so
  Expected in:     <DAEF2BE1-BBB4-3005-8003-63A504CDB9D9> /Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: dlopen(/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: <EFEA74AA-44F5-3C18-ACDE-569DC74B4C4B> /Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so
  Expected in:     <11AF69D2-D297-3A71-9726-5890F112453F> /Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch/lib/libc10.dylib
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/Users/songyunchong/miniforge3/envs/test/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: <EFEA74AA-44F5-3C18-ACDE-569DC74B4C4B> /Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so
  Expected in:     <11AF69D2-D297-3A71-9726-5890F112453F> /Users/songyunchong/miniforge3/envs/test/lib/python3.9/site-packages/torch/lib/libc10.dylib
```

I also tried using `pip install torch_scatter torch_sparse` after uninstall previous packages, but got same error as before, can you help me?

**Comment by rusty1s** [comment]
Mh, does the same error appear if you are using `torch==2.0.0`? This likely suggests that there is a mismatch between PyTorch versions, but I am not yet sure why this might be the case for you.

**Comment by realCrush** [comment]
I tried using `torch==2.0.0`, it doesn't work, I also tried to install all the packages using `pip` instead of `conda`, still got the same error 😢.

**Comment by realCrush** [comment]
BTW, as you mentioned in the [release note of PyG 2.3.0](https://github.com/pyg-team/pytorch_geometric/releases/tag/2.3.0), the latest `PyG` could replace the `torch_sparse` and `torch_scatter` packages with PyTorch native implementation, can I ask your developing plan for `torch_sparse` and `torch_scatter`? they are really useful, but seem to lag a bit on the development of new features, e.g., the document and many functions for `SparseTensor` is still lacking. I'm afraid the situation would become worse after `PyG 2.3.0`.

**Comment by rusty1s** [comment]
Can you try to compile from source by just running
```
pip install --verbose torch-scatter
```
Let me know the error logs in case you received one.

We will still support `torch-scatter` and `torch-sparse` and add features to it, but it is not a high priority from our side anymore. The vast majority of work will go into https://github.com/pyg-team/pyg-lib, and we are moving a lot of functionality from `torch-sparse` to this as well. This also comes with better documentation and nightly builds to test new features quickly.

**Comment by realCrush** [comment]
Hi, I've tried added `--verbose` tag, still got the same errors:
```zsh
$ pip uninstall torch-scatter torch-sparse
$ pip install --verbose torch-scatter
$ pip install --verbose torch-sparse
$ python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torch_geometric, torch_sparse
/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: dlopen(/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_scatter/_scatter_cpu.so, 0x0006): Symbol not found: __ZN2at4_ops6narrow4callERKNS_6TensorExxx
  Referenced from: <40C9EA45-5166-3704-94F1-8C3ED6EBA15C> /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_scatter/_scatter_cpu.so
  Expected in:     <DAEF2BE1-BBB4-3005-8003-63A504CDB9D9> /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: dlopen(/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: <EFEA74AA-44F5-3C18-ACDE-569DC74B4C4B> /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so
  Expected in:     <11AF69D2-D297-3A71-9726-5890F112453F> /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch/lib/libc10.dylib
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: <EFEA74AA-44F5-3C18-ACDE-569DC74B4C4B> /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse/_diag_cpu.so
  Expected in:     <11AF69D2-D297-3A71-9726-5890F112453F> /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch/lib/libc10.dylib
```

**Comment by realCrush** [comment]
> We will still support `torch-scatter` and `torch-sparse` and add features to it, but it is not a high priority from our side anymore. The vast majority of work will go into https://github.com/pyg-team/pyg-lib, and we are moving a lot of functionality from `torch-sparse` to this as well. This also comes with better documentation and nightly builds to test new features quickly.

Thank you for your explanation.

**Comment by rusty1s** [comment]
Yes, but what does the installation log say? Please keep in mind that you need to uninstall previous versions beforehand.

**Comment by realCrush** [comment]
The full log is here:
```zsh
(s4g) [Crushs-MacBook-Pro 23-05-30 23:24] $ pip uninstall torch-scatter torch-sparse
Found existing installation: torch-scatter 2.1.1
Uninstalling torch-scatter-2.1.1:
  Would remove:
    /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_scatter-2.1.1.dist-info/*
    /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_scatter/*
Proceed (Y/n)? y
  Successfully uninstalled torch-scatter-2.1.1
Found existing installation: torch-sparse 0.6.17
Uninstalling torch-sparse-0.6.17:
  Would remove:
    /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse-0.6.17.dist-info/*
    /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/torch_sparse/*
Proceed (Y/n)? y
  Successfully uninstalled torch-sparse-0.6.17
(s4g) [Crushs-MacBook-Pro 23-05-30 23:28] $ pip install --verbose torch-sparse
Using pip 23.1.2 from /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/pip (python 3.9)
Collecting torch-sparse
  Using cached torch_sparse-0.6.17-cp39-cp39-macosx_11_0_arm64.whl
Requirement already satisfied: scipy in /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages (from torch-sparse) (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages (from scipy->torch-sparse) (1.24.3)
Installing collected packages: torch-sparse
Successfully installed torch-sparse-0.6.17
(s4g) [Crushs-MacBook-Pro 23-05-30 23:28] $ pip install --verbose torch-scatter     
Using pip 23.1.2 from /Users/songyunchong/miniforge3/envs/s4g/lib/python3.9/site-packages/pip (python 3.9)
Collecting torch-scatter
  Using cached torch_scatter-2.1.1-cp39-cp39-macosx_11_0_arm64.whl
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.1.1
```

**Comment by realCrush** [comment]
> It uses a cached installation, so please try via
> 
> ```
> pip install --no-cache-dir --verbose torch-scatter
> ```

Thanks! It works! 🥳
