### ISSUE TITLE
Error importing torch_sparse 

### ISSUE THREAD

**Issue by ericyj-lee** [rusty1s/pytorch_sparse#348]
**I installed the PyG package using pip instructions on the website and checked my pip list,  showing** 
torch                    2.0.1+cu118
torch-cluster            1.6.3+pt20cu118
torch_geometric          2.4.0
torch-scatter            2.1.2+pt20cu118
torch-sparse             0.6.18+pt20cu118
torch-spline-conv        1.2.2+pt20cu118

**However, when doing all the import,**
"import torch_cluster 
print("torch_cluster",torch_cluster.__version__)
import torch_scatter
print("torch_scatter",torch_scatter.__version__)
import torch_spline_conv 
print("torch_spline_conv ",torch_spline_conv .__version__)
import torch_geometric
print("torch_geometric",torch_geometric.__version__)
import torch_sparse 
print("torch_sparse",torch_sparse.__version__)"

**Only torch_sparse shows the error of "Traceback (most recent call last):**
  File "<string>", line 1, in <module>
  File "/home/ericylee/.local/lib/python3.10/site-packages/torch_sparse/__init__.py", line 39, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/ericylee/.local/lib/python3.10/site-packages/torch_sparse/storage.py", line 7, in <module>
    from torch_sparse.utils import Final, index_sort
  File "/home/ericylee/.local/lib/python3.10/site-packages/torch_sparse/utils.py", line 5, in <module>
    import torch_sparse.typing
  File "/home/ericylee/.local/lib/python3.10/site-packages/torch_sparse/typing.py", line 2, in <module>
    import pyg_lib  # noqa
  File "/home/ericylee/.local/lib/python3.10/site-packages/pyg_lib/__init__.py", line 39, in <module>
    load_library('libpyg')
  File "/home/ericylee/.local/lib/python3.10/site-packages/pyg_lib/__init__.py", line 36, in load_library
    torch.ops.load_library(spec.origin)
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/sw/pkgs/arc/python/3.10.4/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/ericylee/.local/lib/python3.10/site-packages/libpyg.so)"

**Comment by ericyj-lee** [comment]
The same error also shows when i downgrade the version to torch-sparse==0.6.17

**Comment by rusty1s** [comment]
Looks to be an issue with `pyg-lib`, which somehow requires `GLIBC_2.29`. For now, you can uninstall it or manually install it from source. I need to look into it. Would be great if you can open this issue on github.com/pyg-team/pyg-lib to track it.
