### ISSUE TITLE
ImportError: Could not find module '_version_cpu', after build from source

### ISSUE THREAD

**Issue by apri0426** [rusty1s/pytorch_sparse#354]
I encounter the issue with glibc version, so I try to build from source, but I get this import error.

I am on Centos7 with python3.11, pytorch2.0 and torch_sparse 0.6.18

Full log:

import torch_sparse

Traceback (most recent call last):
  File "\<stdin\>", line 1, in \<module\>
  File "/home/myname/pytorch_sparse/torch_sparse/__init__.py", line 20, in \<module\>
    raise ImportError(f"Could not find module '{library}_cpu' in "
ImportError: Could not find module '_version_cpu' in /home/myname/pytorch_sparse/torch_sparse

**Comment by apri0426** [comment]
it turns out that __file__ doesn't correctly recognize the path and returns none, so after manually specify the path, I was able to solve the issue
