### ISSUE TITLE
Unable to install torch-sparse (Windows 10, CUDA 10.1)

### ISSUE THREAD

**Issue by jcalebsmith** [rusty1s/pytorch_sparse#42]
Windows 10
CUDA 10.1
PyTorch 1.4.0

I'm having issues getting torch-sparse installed. Any ideas?

**Issue 1**: 
```
pip install torch-scatter==latest+cu101  torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0
.html
```

**Returns**
Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
ERROR: Could not find a version that satisfies the requirement torch-scatter==latest+cu101 (from versions: latest+cpu, 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3
.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.3+cpu, 2.0.4, 2.0.4+cpu)
ERROR: No matching distribution found for torch-scatter==latest+cu101

**Issue 2**: When attempting to install from source, `pip install torch-sparse`

**Returns**
Collecting torch-sparse
  Using cached torch_sparse-0.6.0.tar.gz (29 kB)
Requirement already satisfied: scipy in c:\users\caleb\anaconda3\envs\graphstar\lib\site-packages (from torch-sparse) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\caleb\anaconda3\envs\graphstar\lib\site-packages (from scipy->torch-sparse) (1.18.1)
Building wheels for collected packages: torch-sparse
...
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\caleb\AppData\Local\Temp\pip-install-yonrwolo\torch-sparse\setup.py", line 81, in <module>
      setup(
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\wheel\bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
      self.run_command('egg_info')
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
      self.find_sources()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
      mm.run()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
      self.add_defaults()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 579, in add_defaults
      self.read_manifest()
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\sdist.py", line 220, in read_manifest
      self.filelist.append(line)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 477, in append
      path = convert_path(item)
    File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\util.py", line 122, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/Users/rusty1s/github/pytorch_sparse/csrc/convert.cpp' cannot be absolute
  ----------------------------------------
  ERROR: Failed building wheel for torch-sparse
  Running setup.py clean for torch-sparse
Failed to build torch-sparse
Installing collected packages: torch-sparse
...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\caleb\AppData\Local\Temp\pip-install-yonrwolo\torch-sparse\setup.py", line 81, in <module>
        setup(
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
        self.find_sources()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
        mm.run()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
        self.add_defaults()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 579, in add_defaults
        self.read_manifest()
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\sdist.py", line 220, in read_manifest
        self.filelist.append(line)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\site-packages\setuptools\command\egg_info.py", line 477, in append
        path = convert_path(item)
      File "C:\Users\caleb\Anaconda3\envs\GraphStar\lib\distutils\util.py", line 122, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/Users/rusty1s/github/pytorch_sparse/csrc/convert.cpp' cannot be absolute
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\caleb\Anaconda3\envs\GraphStar\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\caleb\\
AppData\\Local\\Temp\\pip-install-yonrwolo\\torch-sparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\caleb\\AppData\\Local\\Temp\\pip-install-yonrwolo\\torch-sparse\\setup.py'"'"';f
=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record '
C:\Users\caleb\AppData\Local\Temp\pip-record-s01gqisg\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\caleb\Anaconda3\envs\GraphStar
\Include\torch-sparse' Check the logs for full command output.

**Comment by rusty1s** [comment]
Mh, I am not sure why `pip` cannot find the package, but you can directly pass in the links any of the links from [here](https://pytorch-geometric.com/whl/torch-1.4.0.html) and see if that fixes your issue.

**Comment by Chethan-Babu-stack** [comment]
I'm facing the same issue and I do not find any solution. Please someone suggest what should be done to resolve this issue.

**Comment by rusty1s** [comment]
You can try to install via the `--no-index` option:
```
pip install --no-index torch-scatter==latest+cu101  torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
.html
```

**Comment by Chethan-Babu-stack** [comment]
The following error message is being shown:


ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'torch-scatter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 82, in from_requirement
    if not cands:
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 38, in _iter_built
    candidate = func()
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 169, in _make_candidate_from_link
    name=name, version=version,
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 288, in __init__
    wheel_version = Version(wheel.version)
  File "c:\users\chethan\anaconda3\lib\site-packages\pip\_vendor\packaging\version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip._vendor.packaging.version.InvalidVersion: Invalid version: 'latest+cu101'

**Comment by Chethan-Babu-stack** [comment]
Is this issue happening because I have an intel processor?

WARNING: Requirement 'torch-sparse==torch_sparse-latest+cu101-cp37-cp37m-win_amd64.whl' looks like a filename, but the file does not exist
Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
ERROR: torch-sparse==torch_sparse-latest+cu101-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by guminyuan** [comment]
I encountered the same issues, both are reproducible quite easily. And I can solve/bypass the problem.
My env is windows 10.
The root cause is python version. I am using python 3.9, which is not yet supported i reckon.
After swapping back to python 3.8, it was installed successfully. 
Hope this helps.

**Comment by jameschapman19** [comment]
thanks @guminyuan. New venv with python 3.8 and all good!

**Comment by sriakhil25** [comment]
> 

(gnn) C:\Users\akhil>pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
Collecting torch-scatter
  Downloading https://data.pyg.org/whl/torch-1.7.0%2Bcpu/torch_scatter-2.0.7-cp37-cp37m-win_amd64.whl (278 kB)
     |████████████████████████████████| 278 kB 36 kB/s
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.7

(gnn) C:\Users\akhil>pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
Collecting torch-sparse
  Downloading https://data.pyg.org/whl/torch-1.7.0%2Bcpu/torch_sparse-0.6.9-cp37-cp37m-win_amd64.whl (533 kB)
     |████████████████████████████████| 533 kB 172 kB/s
Requirement already satisfied: scipy in c:\users\akhil\.conda\envs\gnn\lib\site-packages (from torch-sparse) (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in c:\users\akhil\.conda\envs\gnn\lib\site-packages (from scipy->torch-sparse) (1.21.5)
Installing collected packages: torch-sparse
Successfully installed torch-sparse-0.6.9

**Comment by sriakhil25** [comment]
> > ```
> > pip install --no-index torch-scatter==latest+cu101  torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
> > ```
> 
> ## Could you please help in following issues
> My torch-geometric was working fine, all of sudden I am getting following error:
> python.exe - Entry Point Not Found
> The procedure entry point could not be located in the dynamic link library C:\Users\akhil.conda\envs\gnn\lib\site-packages\torch_sparse_version_cpu.pyd.
> 
> I created a separate conda environment installed torch-sparse with following command but issue persists. pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html

Hi All,

Please ignore. I created a new conda environment and installed pyg now its working

**Comment by gauravsingh16** [comment]
error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Gaurav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Gaurav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Gaurav\AppData\Local\Temp\pip-build-env-09p4bgi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Gaurav\AppData\Local\Temp\pip-build-env-09p4bgi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\Gaurav\AppData\Local\Temp\pip-build-env-09p4bgi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Gaurav\AppData\Local\Temp\pip-build-env-09p4bgi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.



##############################################################
I am getting this error, I have python version 3.10 . IDK why this is saying torch not found, I have already installed torch .

**Comment by rusty1s** [comment]
For installation from source, you need to have `torch` installed beforehand.
