### ISSUE TITLE
import unique_cuda error while 'from torch_sparse import coalesce'

### ISSUE THREAD

**Issue by ihollywhy** [rusty1s/pytorch_sparse#6]
Hi,

When I install this package using pip and what to import it in python, I got the following error:

Do you have any idea about how to solve it?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yiding/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch_sparse/__init__.py", line 1, in <module>
    from .coalesce import coalesce
  File "/home/yiding/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 4, in <module>
    from .utils.unique import unique
  File "/home/yiding/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch_sparse/utils/unique.py", line 5, in <module>
    import unique_cuda
ImportError: /home/yiding/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/unique_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE

**Comment by rusty1s** [comment]
Related https://github.com/rusty1s/pytorch_scatter/issues/7
