### ISSUE TITLE
Import error on Windows 10 when using Python 3.8+

### ISSUE THREAD

**Issue by marijnvk** [rusty1s/pytorch_sparse#60]
When trying to import PyG's `GCNConv`, I run into the following `torch-sparse` error:

```
Traceback (most recent call last):
  File "yard_train.py", line 15, in <module>
    from yard_net import YardNet
  File "C:\Users\<username>\Desktop\yard\yard_net.py", line 6, in <module>
    from torch_geometric.nn import GCNConv
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_sparse\__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\<username>\Miniconda3\envs\<env_name>\Lib\site-packages\torch_sparse\_convert.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

A straight-forward import from the console fails in the same manner:
```
Python 3.8.2 (default, Apr 14 2020, 19:01:40) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_sparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch_sparse\__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "C:\Users\<username>\Miniconda3\envs\<env_name>\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\<username>\Miniconda3\envs\<env_name>\Lib\site-packages\torch_sparse\_convert.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

Checking the directory in question reveals that `_convert.pyd` does exist at the mentioned path, and the only dependency I see in the documentation (`torch-scatter`) is installed. The installation of both packages was completed without any problems.

I have the following versions installed:
```
Windows 10
Python 3.8.2
Pytorch 1.5.0
torch-scatter 2.0.4
torch-sparse 0.6.2
CUDA 10.1
```

**Comment by marijnvk** [comment]
Apparently, [the way Python handles importing DLLs changed in Python 3.8](https://stackoverflow.com/a/58632354). Could this be the cause?

**Comment by rusty1s** [comment]
That's interesting. Can you apply the modifications mentioned in the thread and see if that fixes your errors?

**Comment by marijnvk** [comment]
If you can tell me which DLLs specifically torch-sparse needs to load, I can make the suggested changes.

**Comment by rusty1s** [comment]
My guess is that it wants to import some DLLs from CUDA and PyTorch. I am not aware of any other dependencies.

**Comment by marijnvk** [comment]
So since `PATH `is no longer automatically included in the list of directories that Python 3.8 checks for DLLs, I figure I'd start by adding them manually with this code:

```
import os
for path in os.environ['PATH'].split(';'):
    try:
        os.add_dll_directory(path)
    except FileNotFoundError:
        print(f"skipping {path}, does not exist")
```

This does indeed fix the issue (though I now see that I have a CUDA version mismatch somewhere else). Going through the paths in `PATH`, I found that it's specifically the following CUDA path that was missing for `torch-sparse`:

`C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin`

So just adding this path solves the issue for me, no need to add the entire content of `PATH`:

```
import os
os.add_dll_directory('C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin')
```

**Comment by rusty1s** [comment]
Great!

**Comment by wzz2579421845** [comment]
> 因此，由于`PATH`Python 3.8不再自动将其包含在用于检查DLL的目录列表中，因此，我认为首先要使用以下代码手动添加它们：
> 
> ```
> import os
> for path in os.environ['PATH'].split(';'):
>     try:
>         os.add_dll_directory(path)
>     except FileNotFoundError:
>         print(f"skipping {path}, does not exist")
> ```
> 
> 确实确实可以解决该问题（尽管我现在看到我在其他地方存在CUDA版本不匹配）。遍历中的路径`PATH`，我发现具体缺少以下CUDA路径`torch-sparse`：
> 
> `C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin`
> 
> 因此，只需添加此路径即可为我解决问题，而无需添加以下内容的全部`PATH`：
> 
> ```
> import os
> os.add_dll_directory('C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin')
> ```

This method is still not acceptable. Is there any other method
