### ISSUE TITLE
RuntimeError: No such operator torch_sparse::cuda_version

### ISSUE THREAD

**Issue by tanjia123456** [rusty1s/pytorch_sparse#83]
Hello, the error message is as follows:
tj@bme01:~/codes/GCNII-master/PyG/cora$ python cora.py
Traceback (most recent call last):
  File "cora.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_sparse/__init__.py", line 24, in <module>
    cuda_version = torch.ops.torch_sparse.cuda_version()
  File "/home/tj/anaconda3/lib/python3.6/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torch_sparse::cuda_version

I suspect that the version of torch_sparse I installed does not match the version of cuda. Do you know how to solve it?
my cuda 10.0, torch1.3.1 cu100, python 3.6.1, The version of torch_sparse I use now is 0.5.1

**Comment by rusty1s** [comment]
It is best to upgrade your PyTorch to a more recent version. Otherwise, you need to install [PyTorch-Sparse 0.4.3](https://github.com/rusty1s/pytorch_sparse/releases/tag/0.4.3): `pip install torch-sparse==0.4.3`.

**Comment by tanjia123456** [comment]
yes, I have installed torch-sparse0.4.3, but another error occurs:  from torch_sparse import SparseTensor, matmul, fill_diag, sum, mul_
ImportError: cannot import name 'SparseTensor'

which version can solve my problem?

**Comment by rusty1s** [comment]
I see. In case you want to use the latest PyG version, you must also install one of the latest torch-sparse releases. The latest PyG version that supports `torch==1.3.1` is `torch-geometric==1.3.2`, see [here](https://github.com/rusty1s/pytorch_geometric/releases/tag/1.3.2).
