### ISSUE TITLE
Expected a default value of type Tensor (inferred) on parameter "tensor".

### ISSUE THREAD

**Issue by wohlbier** [rusty1s/pytorch_sparse#87]
Any insight?

```
Traceback (most recent call last):
  File "sign.py", line 8, in <module>
    import torch_geometric.transforms as T
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_geometric-1.6.1-py3.8.egg/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_geometric-1.6.1-py3.8.egg/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_geometric-1.6.1-py3.8.egg/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_geometric-1.6.1-py3.8.egg/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_geometric-1.6.1-py3.8.egg/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_sparse-0.6.7-py3.8-linux-x86_64.egg/torch_sparse/__init__.py", line 35, in <module>
    from .tensor import SparseTensor  # noqa
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_sparse-0.6.7-py3.8-linux-x86_64.egg/torch_sparse/tensor.py", line 11, in <module>
    class SparseTensor(object):
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch/jit/_script.py", line 924, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch/jit/_script.py", line 64, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
Expected a default value of type Tensor (inferred) on parameter "tensor".Because "tensor" was not annotated with an explicit type it is assumed to be type 'Tensor'.:
  File "/DATA/SDH/packages/anaconda3/envs/twit_profile_env/lib/python3.8/site-packages/torch_sparse-0.6.7-py3.8-linux-x86_64.egg/torch_sparse/tensor.py", line 126
    def type_as(self, tensor=torch.Tensor):
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        value = self.storage.value()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        if value is None or tensor.dtype == value.dtype:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            return self
            ~~~~~~~~~~~
        return self.from_storage(self.storage.type_as(tensor))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

**Comment by rusty1s** [comment]
When does this error occur?

**Comment by wohlbier** [comment]
I will give some more context soon. I'm wondering, however, about line 126. Should that be `=` or `:`? I see the pattern used elsewhere with `:`.

**Comment by rusty1s** [comment]
I see, that's indeed a typo. Weird, it does not throw an error for me. I fixed it in `torch-sparse` master. You may want to fix it locally for yourself :)

**Comment by wohlbier** [comment]
Indeed, the code runs without error with that change 👍
