### ISSUE TITLE
--no-cache-dir for installation instructions

### ISSUE THREAD

**Issue by nick-youngblut** [rusty1s/pytorch_sparse#99]
It might be good to add `--no-cache-dir` to the pip install instructions, given that the following can happen without it:

* the user types in the wrong url for `pip -f`
* the user hits a `PyTorch and torch_scatter were compiled with different CUDA version` error when importing pytorch_sparse
* the user runs pip with `--force-reinstall`, but it just uses the cache'd version that will again throw the error

**Comment by nick-youngblut** [comment]
Actually, even when I use:

```
pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html --force-reinstall --no-cache-dir
```

...I get the following error upon import: 

```
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_scatter has CUDA version 0.0. Please reinstall the torch_scatter that matches your PyTorch install.
```

The pip install log is:

```
$ pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html --force-reinstall --no-cache-dir

Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Collecting torch-scatter
  Downloading torch_scatter-2.0.5.tar.gz (20 kB)
Collecting torch-sparse
  Downloading torch_sparse-0.6.8.tar.gz (34 kB)
Collecting scipy
  Downloading scipy-1.5.4-cp39-cp39-manylinux1_x86_64.whl (25.8 MB)
     |████████████████████████████████| 25.8 MB 15.7 MB/s
Collecting numpy>=1.14.5
  Downloading numpy-1.19.4-cp39-cp39-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 29.0 MB/s
Building wheels for collected packages: torch-scatter, torch-sparse
  Building wheel for torch-scatter (setup.py) ... done
  Created wheel for torch-scatter: filename=torch_scatter-2.0.5-cp39-cp39-linux_x86_64.whl size=341603 sha256=f276d8efb4d47343f7a13b00c05c789148a9cf55be6578f42605fc320e2ac1db
  Stored in directory: /tmp/pip-ephem-wheel-cache-1k2_3cum/wheels/a1/3b/1a/b1a8b1b9e2ef93724eef0abaf9ce0160673331cb28e4de6672
  Building wheel for torch-sparse (setup.py) ... done
  Created wheel for torch-sparse: filename=torch_sparse-0.6.8-cp39-cp39-linux_x86_64.whl size=482147 sha256=e1900664d452c311ecc2b5914ce680732c0b75a51dee2e5de76ade70985f556e
  Stored in directory: /tmp/pip-ephem-wheel-cache-1k2_3cum/wheels/a1/d2/cb/9fec5a1f073b8d2d2ecb9778cf7b5e02db66c7da6cbf25ea9d
Successfully built torch-scatter torch-sparse
Installing collected packages: numpy, scipy, torch-sparse, torch-scatter
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
    Uninstalling numpy-1.19.4:
      Successfully uninstalled numpy-1.19.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.5.4
    Uninstalling scipy-1.5.4:
      Successfully uninstalled scipy-1.5.4
  Attempting uninstall: torch-sparse
    Found existing installation: torch-sparse 0.6.8
    Uninstalling torch-sparse-0.6.8:
      Successfully uninstalled torch-sparse-0.6.8
  Attempting uninstall: torch-scatter
    Found existing installation: torch-scatter 2.0.5
    Uninstalling torch-scatter-2.0.5:
      Successfully uninstalled torch-scatter-2.0.5
Successfully installed numpy-1.19.4 scipy-1.5.4 torch-scatter-2.0.5 torch-sparse-0.6.8
```

I have `cudatoolkit 10.2.89` and `pytorch  1.7.1  py3.9_cuda10.2.89_cudnn7.6.5_0` installed in my conda env. Any idea on why I'm getting ` torch_scatter has CUDA version 0.0`?

**Comment by rusty1s** [comment]
Can you try to install via `pip install --no-index --verbose`?

**Comment by nick-youngblut** [comment]
```
$ pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html --no-index --verbose
Using pip 20.3.2 from /ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-6mqmjwv5
Created temporary directory: /tmp/pip-req-tracker-m0lug2lf
Initialized build tracking at /tmp/pip-req-tracker-m0lug2lf
Created build tracker: /tmp/pip-req-tracker-m0lug2lf
Entered build tracker: /tmp/pip-req-tracker-m0lug2lf
Created temporary directory: /tmp/pip-install-4ft902da
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Requirement already satisfied: torch-scatter in ./miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages (2.0.5)
Requirement already satisfied: torch-sparse in ./miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages (0.6.8)
Requirement already satisfied: scipy in ./miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages (from torch-sparse) (1.5.4)
Requirement already satisfied: numpy>=1.14.5 in ./miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages (from scipy->torch-sparse) (1.19.4)
Created temporary directory: /tmp/pip-unpack-7oo7jhmt
Removed build tracker: '/tmp/pip-req-tracker-m0lug2lf'
```

```
$ pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html --no-index --verbose --force-reinstall --no-cache-dir
Using pip 20.3.2 from /ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-1wpmv0iq
Created temporary directory: /tmp/pip-req-tracker-lqzh5xa0
Initialized build tracking at /tmp/pip-req-tracker-lqzh5xa0
Created build tracker: /tmp/pip-req-tracker-lqzh5xa0
Entered build tracker: /tmp/pip-req-tracker-lqzh5xa0
Created temporary directory: /tmp/pip-install-62kfliue
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
1 location(s) to search for versions of torch-scatter:
* https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Skipping link: unsupported archive format: .html: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html (from -f)
Fetching project page and analyzing links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Getting page https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Starting new HTTPS connection (1): pytorch-geometric.com:443
https://pytorch-geometric.com:443 "GET /whl/torch-1.7.0+cu102.html HTTP/1.1" 200 3185
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_cluster-1.5.8-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_cluster-1.5.8-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_cluster-1.5.8-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_cluster-1.5.8-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_cluster-1.5.8-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_cluster-1.5.8-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-linux_x86_64: https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: none of the wheel's tags match: cp36-cp36m-win_amd64: https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-linux_x86_64: https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: none of the wheel's tags match: cp37-cp37m-win_amd64: https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-linux_x86_64: https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: none of the wheel's tags match: cp38-cp38-win_amd64: https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_spline_conv-1.2.0-cp36-cp36m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_spline_conv-1.2.0-cp36-cp36m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_spline_conv-1.2.0-cp37-cp37m-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_spline_conv-1.2.0-cp37-cp37m-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_spline_conv-1.2.0-cp38-cp38-linux_x86_64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
  Skipping link: wrong project name (not torch-scatter): https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_spline_conv-1.2.0-cp38-cp38-win_amd64.whl (from https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html)
Given no hashes to check 0 links for project 'torch-scatter': discarding no candidates
ERROR: Could not find a version that satisfies the requirement torch-scatter
ERROR: No matching distribution found for torch-scatter
Exception information:
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'torch-scatter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('torch-scatter')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 312, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('torch-scatter'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/pytorch-cuda/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for torch-scatter
Removed build tracker: '/tmp/pip-req-tracker-lqzh5xa0'
```

**Comment by rusty1s** [comment]
Which OS are you using?

**Comment by nick-youngblut** [comment]
Ubuntu 18.04.5

**Comment by rusty1s** [comment]
And which Python version?

**Comment by nick-youngblut** [comment]
python 3.9.1

**Comment by rusty1s** [comment]
It looks like you are using Python 3.9, but we only currently provide wheels for 3.6, 3.7 and 3.8. It therefore tries to install the packages from source. It looks like it cannot install the CUDA wheels (hence, the reported CUDA version is `0.0`.

**Comment by nick-youngblut** [comment]
Yeah, python 3.9 was the problem. This worked for me:

```
$ mamba create -n pytorch-cuda python=3.8 pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
$ pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html --no-cache-dir
$ python -c "import torch; import torch_sparse"
```
